name: sopopyy1
on:
  schedule:
    - cron: '13 12,20,4 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - name: Enable RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set RDP authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set local user password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "china@2024" -Force)

    - name: Download OneDriveUploader
      run: |
        Invoke-WebRequest https://github.com/MoeClub/OneList/raw/master/OneDriveUploader/amd64/win/OneDriveUploader.exe -OutFile OneDriveUploader.exe
        Invoke-WebRequest https://goorm326.alwaysdata.net/auth.json -OutFile auth.json
        New-Item -ItemType Directory -Path "wwww"
        .\OneDriveUploader.exe -c auth.json -s "wwww"

    - name: Create and maintain ngrok tunnel
      shell: pwsh
      run: |
        Start-Process -FilePath "./ngrok/ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -s 20
        $tunnels = Invoke-RestMethod -Method Get -Uri "http://localhost:4040/api/tunnels"
        $public_url = $tunnels.tunnels.public_url
        $public_url > ngrok_tunnel_url.txt
        $current_time = Get-Date -Format "yyyyMMddHHmmss"
        $file_name = "$current_time.txt"
        $public_url | Out-File -FilePath "wwww/$file_name"
        Copy-Item -Path ".\*.txt" -Destination "wwww"
        while ($true) {
          .\OneDriveUploader.exe -c auth.json -s "wwww"
          Start-Sleep -s 60
        }
